version: '3.8'

services:
    database:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root1234
            MYSQL_DATABASE: pcdepotShop
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql1234
        volumes:
            - 'D:/data/mysql-data:/var/lib/mysql'
        ports:
            - '3306:3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: root1234
        ports:
            - '5050:80'
        depends_on:
            - database
